name: Code Climate Test Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov codeclimate-test-reporter

    - name: Run Tests and Generate Coverage Report
      run: |
        pytest --cov=. --cov-report=xml

    - name: Upload Coverage to Code Climate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        codeclimate-test-reporter format-coverage --input-type coverage.py --output coverage.json
        codeclimate-test-reporter upload-coverage
